# Add 'repo' label to any root file changes
app:
  - ./app.py

Dockerfile:
  - ./Dockerfile

requirements:
  - ./requirements.txt

jupyter:
  - ./*.ipynb

# Add 'test' label to any change to *.spec.js files within the source dir
github:
  - .github/**/*
